FROM sigrist/wiremock

EXPOSE 9999

#ENTRYPOINT ["java", "-jar", "/opt/wiremock/wiremock-standalone-2.*.jar", "--port 9999"]
ENTRYPOINT ["java", "-jar", "/opt/wiremock/wiremock-standalone-2.6.0.jar", " --port=9999"]
